name: flashcard_app
description: Flutter app for flashcards with SRS and AI generation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  # Navigation
  go_router: ^13.2.0

  # iOS-style UI
  cupertino_icons: ^1.0.8
  cupertino_native: ^0.1.1
  # Network
  dio: ^5.4.3

  # Env
  flutter_dotenv: ^5.1.0

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.0

  # Storage
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # UI
  flip_card: ^0.7.0
  file_picker: ^8.0.3
  lottie: ^3.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  fl_chart: ^0.66.0

  # Utils
  uuid: ^4.3.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env.debug
